Month9/step1
ADudin/react-stellar-burger pull request #5
Opened 2023-07-11 18:48 UTC by ADudin

2023-07-16 11:50 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Роуты записаны в константы
- Есть автологин
- Реализовали обновление токена при протухании
- Защита роутов реализована в одном компоненте 

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- При сохранении данных формы на странице профиля происходит перезагрузка страницы
- Если пользователь не авторизован и пытается попасть на защищённый маршрут — его переадресовывает на маршрут `/login`. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него не получилось получить доступ ранее. Это делается с помощью ` return <Navigate to={location?.state?.from || '/'} />;` (эти данные записываются в `ProtectedRoute`, а используются в `Login` для `Navigate`)

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-07-16 11:50 UTC, andryxxa93 commented on src/components/app/app.jsx
> +    if (localStorage.getItem('accessToken')) {
**Можно лучше**
Строка `accessToken ` и `refreshToken` очень часто повторяются в проекте, чтобы случайно не допустить ошибку и потом долго её дебажить - лучше записывать такие строки в константы

2023-07-16 11:50 UTC, andryxxa93 commented on src/pages/fogot-password/fogot-password.jsx
> +  const onChange = evt => {
**Можно лучше**

Можно сделать универсальный **кастомный** хук для контроля любого количества инпутов в любых формах:
```js
 export function useForm(inputValues) {
   const [values, setValues] = useState(inputValues);
 
   const handleChange = (event) => {
     const {value, name} = event.target;
     setValues({...values, [name]: value});
   };
   return {values, handleChange, setValues};
 }
```
    
Этот код помещают в отдельный файл `useForm.js` в папке `hooks` и импортируют функцию туда, где нужно контролировать инпуты

 И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:
    
 ```js
   const {values, handleChange, setValues} = useForm({});
 ```

2023-07-16 17:59 UTC, ADudin commented on src/pages/fogot-password/fogot-password.jsx
> +  const onChange = evt => {
С маршрутом, там другая история получилась, эта логика уже реализована в HOC ProtectedRoutes. Я эти пути для авторизованных пользователей уже в конце делал, а до этого, когда вообще маршруты подключал и перелинковку делал, в хедере сделал функцию проверки авторизации пользователя. Она данные из redux брала и меняла маршрут с '/profile' на '/', если пользователь не авторизован. Я ее забыл убрать просто, после того как HOC настроил. Теперь все работает.

2023-07-17 08:41 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-07-17 17:18 UTC, merged